version: '3.9'

networks:
    qgis:

services:
    nginx:
        image: nginx:1.13
        ports:
            - '8888:80'
        volumes:
            - ./qgis-server/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - qgis

    qgis-server:
        build:
            context: .
            dockerfile: ./qgis-server/dockerfile
        tty: true
        volumes:
            - ./qgis-server/data:/data:ro
        ports:
          - '5555:5555'
        environment:
            - LANG=en_EN.UTF-8
            - QGIS_PROJECT_FILE=/data/sample.qgz
            - QGIS_SERVER_LOG_LEVEL=0  # INFO (log all requests)
            - DEBUG=1                  # display env before spawning QGIS Server
        networks:
            - qgis